// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd3rFpL4IFiXxjoItxq16gxDcP-aBWxtQ',
    appId: '1:374509133605:web:f813240144b81d639104cc',
    messagingSenderId: '374509133605',
    projectId: 'e-commerce-app-a92ae',
    authDomain: 'e-commerce-app-a92ae.firebaseapp.com',
    storageBucket: 'e-commerce-app-a92ae.appspot.com',
    measurementId: 'G-KB7DK3JZ4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATc4K2U2y15q5wl28OV6wPJ0s3kar8B-s',
    appId: '1:374509133605:android:7e4e9d96d9664c9b9104cc',
    messagingSenderId: '374509133605',
    projectId: 'e-commerce-app-a92ae',
    storageBucket: 'e-commerce-app-a92ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2oOBFFb5DLuHcRRssqBmkz49VBklwrmA',
    appId: '1:374509133605:ios:adc8b406ca8da1879104cc',
    messagingSenderId: '374509133605',
    projectId: 'e-commerce-app-a92ae',
    storageBucket: 'e-commerce-app-a92ae.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2oOBFFb5DLuHcRRssqBmkz49VBklwrmA',
    appId: '1:374509133605:ios:adc8b406ca8da1879104cc',
    messagingSenderId: '374509133605',
    projectId: 'e-commerce-app-a92ae',
    storageBucket: 'e-commerce-app-a92ae.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd3rFpL4IFiXxjoItxq16gxDcP-aBWxtQ',
    appId: '1:374509133605:web:39db056bed633c339104cc',
    messagingSenderId: '374509133605',
    projectId: 'e-commerce-app-a92ae',
    authDomain: 'e-commerce-app-a92ae.firebaseapp.com',
    storageBucket: 'e-commerce-app-a92ae.appspot.com',
    measurementId: 'G-PZHL22046Y',
  );
}
